apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: ghcr.io/jasontanks/service-b:latest
          ports:
            - containerPort: 5000
