apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b
spec:
  project: default
  source:
    repoURL: https://github.com/jasontanks/infra-k8s
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
